Implemented authentication for start requests providing urls.
id-contact/core pull request #19
Opened 2021-09-07 07:29 UTC by davidv1992

2021-09-08 14:35 UTC, hdoordt commented on src/config.rs
> +                        );
```suggestion
                    let key = Box::<dyn JwsVerifier>::try_from(key).unwrap_or_else(|_| {
                        log::error!(
                            "Could not parse requestor key for requestor {}",
                            requestor
                        );
```

Logging the error value might leak the key

2021-09-08 14:42 UTC, hdoordt requested changes
Please make sure no keys are leaked

2021-09-09 08:56 UTC, davidv1992 commented
Fixed the key leak

2021-09-16 05:33 UTC, hdoordt approved these changes

2021-09-16 05:33 UTC, merged